name = "selftest"
description = "Functional tests"
version = "0.1.0-dev"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["selftest"]

[build-profiles]
"*" = "validation"

[build-switches]
"*".ada_version = ["-gnat2022", "-gnatx"]

[[depends-on]]
den = "*"

[[pins]]
den = { path='..' }
